### ISSUE TITLE
Model Tab Doesn't Update After First Model

### ISSUE THREAD

**Issue by thomascjohnson** [radiant-rstats/radiant.model#2]
I was playing around with the logistic regression model and noticed it didn't re-run the estimation when I changed things and hit estimate.

I will try to fix this myself and send a pull request, FYI

**Comment by vnijs** [comment]
That is very odd. It works fine for me. What version of radiant (or radiant.model) are you using?

**Comment by vnijs** [comment]
Just to be clear ... I'm happy to look into this but please describe (in detail) a reproducible example (with data) of the issue you are having *before* submitting a pull request.

**Comment by thomascjohnson** [comment]
Ok, strange, it does work now. I had it happen a few times yesterday and now it works fine.

**Comment by vnijs** [comment]
OK. Thanks. Happy to look into this if you can create a reproducible example.
