### ISSUE TITLE
object ‘cividis’ is not exported by 'namespace:viridisLite'

### ISSUE THREAD

**Issue by msberends** [radiant-rstats/radiant.model#3]
You should note that Radiant has a dependency of viridisLite >= 0.3.0.
When you now install Radiant (from CRAN or even https://radiant-rstats.github.io/minicran) you get the error  
```
object ‘cividis’ is not exported by 'namespace:viridisLite'
```
if viridisLite is outdated.

It is because `cividis` is only being exported by viridisLite version 0.3.0 and later. You should edit you DESCRIPTION file.

**Comment by vnijs** [comment]
Thanks for the report @msberends. Radiant doesn't actually have a direct dependency on `vidrisLite`. However, it does use `DiagrammeR`. I have pushed some updates to GitHub and you should now be able to install and update using either of the commands below. I plan to submit updates to CRAN in the next couple of weeks.

`install.packages("radiant", repos = "https://radiant-rstats.github.io/minicran/")`

or

`source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")`

**Comment by vnijs** [comment]
@msberends The issue should be fixed now. If you still see an issue feel free to reopen the issue
